<?xml version="1.0"?>

<robot name="go1" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="DEBUG" default="false"/>

    <xacro:include filename="$(find go1_description)/xacro/const.xacro"/>
    <xacro:include filename="$(find go1_description)/xacro/materials.xacro"/>
    <xacro:include filename="$(find go1_description)/xacro/leg.xacro"/>
    <!-- <xacro:include filename="$(find go1_description)/xacro/stairs.xacro"/> -->
    <xacro:include filename="$(find go1_description)/xacro/gazebo.xacro"/>
    <!-- <xacro:include filename="$(find go1_description)/xacro/depthCamera.xacro"/> -->
    <!-- <xacro:include filename="$(find go1_gazebo)/launch/stairs.urdf.xacro"/> -->

    <!-- <xacro:stairs stairs="15" xpos="0" ypos="0" zpos="0" /> -->

    <!-- Rollover Protection mode will add an additional stick on the top, use "true" or "false" to switch it. -->
    <xacro:property name="rolloverProtection" value="false"/>

    <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
    <xacro:if value="$(arg DEBUG)">
        <link name="world"/>
        <joint name="base_static_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="base"/>
        </joint>
    </xacro:if> 

    <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="floating_base" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base"/>
        <child link="trunk"/>
    </joint>
    <link name="trunk">
          <inertial>
            <origin
              xyz="0.0052 0.0037 -0.0010"
              rpy="0 0 0" />
            <mass
              value="13.1698" />
            <inertia
              ixx="0.1260"
              ixy="0.0242"
              ixz="-0.0129"
              iyy="0.5315"
              iyz="-0.0014"
              izz="0.5708" />
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
              <box size="0.001 0.001 0.001"/>
          </geometry>
        </visual>
    </link>
    <joint name="trunk_oriented" type="fixed">
        <origin rpy="0 0 1.5707" xyz="0 0 0"/>
        <parent link="trunk"/>
        <child link="trunk_original"/>
    </joint>


    <link
    name="trunk_original">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <box size="0.3 0.3 0.2"/>
        <!-- <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/base_link.STL" /> -->
      </geometry>
    </collision>
  </link>
  <link
    name="battery_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/battery_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/battery_link.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="battery"
    type="fixed">
    <origin
      xyz="-0.0375 0.18558 0.0938526402504663"
      rpy="0 1.5707963267949 0" />
    <parent
      link="trunk_original" />
    <child
      link="battery_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <!-- <link
    name="camera_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/camera_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/camera_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="camera"
    type="fixed">
    <origin
      xyz="0 0.31208 -0.0795"
      rpy="1.5707963267949 0 0" />
    <parent
      link="trunk_original" />
    <child
      link="camera_link" />
    <axis
      xyz="0 0 0" />
  </joint> -->

  <link
    name="FR_hip_rotor_joint_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/FR_hip_rotor_joint_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/FR_hip_rotor_joint_link.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="FR_hip_rotor_joint"
    type="fixed">
    <origin
      xyz="-0.13 -0.145499999999996 0"
      rpy="1.5707963267949 0 3.14159265358979" />
    <parent
      link="trunk_original" />
    <child
      link="FR_hip_rotor_joint_link" />
    <axis
      xyz="0 0 0" />
  </joint>

  <link
    name="FL_hip_rotor_joint_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/FL_hip_rotor_joint_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/FL_hip_rotor_joint_link.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="FL_hip_rotor_joint"
    type="fixed">
    <origin
      xyz="0.13 -0.145499999999996 0"
      rpy="-1.5707963267949 0 0" />
    <parent
      link="trunk_original" />
    <child
      link="FL_hip_rotor_joint_link" />
    <axis
      xyz="0 0 0" />
  </joint>

  <link
    name="RR_hip_rotor_joint_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/RR_hip_rotor_joint_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/RR_hip_rotor_joint_link.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="RR_hip_rotor_joint"
    type="fixed">
    <origin
      xyz="-0.13 0.1455 0"
      rpy="-1.5707963267949 0 3.14159265358979" />
    <parent
      link="trunk_original" />
    <child
      link="RR_hip_rotor_joint_link" />
    <axis
      xyz="0 0 0" />
  </joint>

  <link
    name="RL_hip_rotor_joint_link">
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/RL_hip_rotor_joint_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/RL_hip_rotor_joint_link.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="RL_hip_rotor_joint"
    type="fixed">
    <origin
      xyz="0.13 0.145500000000004 0"
      rpy="-1.5707963267949 0 3.14159265358979" />
    <parent
      link="trunk_original" />
    <child
      link="RL_hip_rotor_joint_link" />
    <axis
      xyz="0 0 0" />
  </joint>

  <link
    name="optitrack_link">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="1E-06" />
      <inertia
        ixx="0"
        ixy="0"
        ixz="0"
        iyy="0"
        iyz="0"
        izz="0" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/optitrack_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://go1_description/meshes/skymul_go1_v2/optitrack_link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="optitrack"
    type="fixed">
    <origin
      xyz="0.000100572552861879 0.055230109658504 0.1138"
      rpy="0 0 0" />
    <parent
      link="trunk_original" />
    <child
      link="optitrack_link" />
    <axis
      xyz="0 0 0" />
  </joint>

  <joint name="rebar_tying_frame" type="fixed">
    <origin rpy="0 0 0" xyz="0.2307 -0.0112 -0.190252"/>
    <parent link="base"/>
    <child link="tying_frame"/>
  </joint>
  <link name="tying_frame">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>


    <xacro:if value="${(rolloverProtection == 'true')}">
        <joint name="stick_joint" type="fixed">
            <parent link="trunk"/>
            <child link="stick_link"/>
            <origin rpy="0 0 0" xyz="${0.18} 0 ${stick_length/2.0+0.08}"/>
        </joint>

        <link name="stick_link">
            <visual>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <!-- <material name="white"/> -->
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${stick_mass}"/>
                <inertia
                    ixx="${stick_mass / 2.0 * (stick_radius*stick_radius)}" ixy="0.0" ixz="0.0"
                    iyy="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}" iyz="0.0"
                    izz="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}"/>                   
            </inertial>
        </link>
    </xacro:if> 

    <joint name="imu_joint" type="fixed">
        <parent link="trunk"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="-0.01592 -0.06659 -0.00617"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <!-- <material name="red"/> -->
        </visual>
        <!-- <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision> -->
    </link>

    <xacro:leg name="FR" mirror="-1" mirror_dae="False" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="0.2118 -0.130 0"/>
    </xacro:leg>

    <xacro:leg name="FL" mirror="1" mirror_dae="True" front_hind="1" front_hind_dae="True">
        <origin rpy="0 0 0" xyz="0.2118 0.130 0"/>
    </xacro:leg>

    <xacro:leg name="RR" mirror="-1" mirror_dae="False" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="-0.2118 -0.130 0"/>
    </xacro:leg>

    <xacro:leg name="RL" mirror="1" mirror_dae="True" front_hind="-1" front_hind_dae="False">
        <origin rpy="0 0 0" xyz="-0.2118 0.130 0"/>
    </xacro:leg>

    <!-- RealSense D435 -->
    <xacro:include filename="$(find go1_description)/xacro/_d435.urdf.xacro" />
    <xacro:sensor_d435 parent="base">
          <origin xyz="0.2 0 0.03" rpy="0 0.50 0" />
    </xacro:sensor_d435>

    <!-- <xacro:depthCamera camID="1" name="face">
        <origin rpy="${PI} 0 0" xyz="0.2785 0.0125 0.0167"/>
    </xacro:depthCamera>

    <xacro:depthCamera camID="2" name="chin">
        <origin rpy="${PI} ${PI/2} 0" xyz="0.2522 0.0125 -0.0436"/>
    </xacro:depthCamera>

    <xacro:depthCamera camID="3" name="left">
        <origin rpy="${PI} 0.2618 ${PI/2}" xyz="-0.066 0.082 -0.0176"/>
    </xacro:depthCamera>

    <xacro:depthCamera camID="4" name="right">
        <origin rpy="${PI} 0.2618 ${-PI/2}" xyz="-0.041 -0.082 -0.0176"/>
    </xacro:depthCamera>

    <xacro:depthCamera camID="5" name="rearDown">
        <origin rpy="${PI} ${PI/2} 0" xyz="-0.0825 0.0125 -0.04365"/>
    </xacro:depthCamera>

    <joint name="camera_laserscan_joint_left" type="fixed">
        <origin rpy="0 0.2618 0" xyz="0 0 0"/>
        <parent link="camera_left"/>
        <child link="camera_laserscan_link_left"/>
    </joint>

    <link name="camera_laserscan_link_left">
    </link>

    <joint name="camera_laserscan_joint_right" type="fixed">
        <origin rpy="0 0.2618 0" xyz="0 0 0"/>
        <parent link="camera_right"/>
        <child link="camera_laserscan_link_right"/>
    </joint>

    <link name="camera_laserscan_link_right">
    </link> -->

</robot>
